language: node_js
node_js:
  - 10.16.0
cache: yarn

install:
  - yarn run installAll
script:
  - yarn -cwd ./client run test
deploy:
  provider: heroku
  api_key:
    secure: 02fd9fe8-39cd-481e-abf9-09fd627f4ae1
  app:  final-project-online-store
  on:
    repo: vashenko49/final_project

